version: "3.9"
services:
  web:
    #depends_on:
    #  - db
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: django-k8s:v1
    ports:
      - "8000:8000"
    command: sh -c "chmod +x migrate.sh && sh migrate.sh && sh entrypoint.sh"
