name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test_django_job:
      uses: RSO-ZKMH/shoppingBasket/.github/workflows/test-django.yaml@main
    build:
      runs-on: ubuntu-latest
      needs: [test_django_job]
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        working-directory: ./admin
        run: docker build -f Dockerfile -t ${{secrets.DOCKER_USER}}/basket-data:latest .

      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USER}}/basket-data

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Target AKS cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          cluster-name: ${{secrets.AZURE_CLUSTER_NAME}}
          resource-group: ${{secrets.AZURE_RESOURCE_GROUP}}
      
      - name: Update Deployment image
        run: |
          kubectl set image deployment/shoppingbasket-deployment shoppingbasket-api=${{secrets.DOCKER_USER}}/basket-data:latest -n rso-deploy
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/shoppingbasket-deployment -n rso-deploy